name: Upload Releases to SourceForge

on:
  workflow_dispatch:

  workflow_run:
    workflows: ['📦 Upload Release Asset']
    types: [completed]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Release Assets
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*'
          out-file-path: release-files

      - name: Verify Downloaded Files
        run: |
          echo "FILES:"
          find release-files

      - name: Upload to SourceForge
        uses: burnett01/rsync-deployments@9.0.0
        with:
          switches: -avzr --delete
          path: release-files/
          remote_path: /home/frs/project/joanium/releases/
          remote_host: frs.sourceforge.net
          remote_user: withinjoel,joanium
          remote_key: ${{ secrets.SF_SSH_KEY }}
